# Generated by Django 2.1rc1 on 2018-07-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DWCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Category Identity')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category')),
                ('category_definition', models.CharField(max_length=500, verbose_name='Definition of the Category')),
            ],
        ),
        migrations.CreateModel(
            name='DWSubcategory',
            fields=[
                ('subcategory_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Subcategory Identity')),
                ('subcategory_name', models.CharField(max_length=100, verbose_name='Subcategory')),
                ('subcategory_explanation', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Base.DWCategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='DWTerms',
            fields=[
                ('term_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Term Identity')),
                ('term_name', models.CharField(max_length=100, verbose_name='Term')),
                ('term_explanation', models.CharField(max_length=1000, verbose_name='Term Explanation')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('example_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Example Identity')),
                ('example_input', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Input')),
                ('example_output', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Output')),
            ],
        ),
        migrations.CreateModel(
            name='RDataSet',
            fields=[
                ('data_set_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Data set Name')),
                ('data_set_description', models.TextField(verbose_name='Description of the data set')),
                ('data_set_format', models.CharField(max_length=1000, verbose_name='Format of the data set')),
                ('data_set_overview', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Data set Overview')),
            ],
        ),
        migrations.CreateModel(
            name='RFunction',
            fields=[
                ('function_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identity')),
                ('function_name', models.CharField(max_length=100, verbose_name='Function Name')),
                ('function_format', models.CharField(max_length=255, verbose_name='Function Code Format')),
                ('function_description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='RPackage',
            fields=[
                ('package_name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='R Package Name')),
                ('package_description', models.CharField(max_length=255, verbose_name='Package Description')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('usage_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Usage Identity')),
                ('usage_format', models.CharField(max_length=255, verbose_name='Function Usage Format')),
                ('usage_description', models.TextField(verbose_name='Function Usage Description')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Base.RFunction', verbose_name='Function')),
            ],
        ),
        migrations.AddField(
            model_name='rfunction',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Base.RPackage', verbose_name='R Package Name'),
        ),
        migrations.AddField(
            model_name='rfunction',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Base.DWSubcategory', verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='example',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Base.RDataSet', verbose_name='Data set'),
        ),
        migrations.AddField(
            model_name='example',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Base.Usage', verbose_name='Usage'),
        ),
    ]
