# Generated by Django 2.1rc1 on 2018-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Base', '0002_auto_20180728_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='example',
            field=models.CharField(default=1, max_length=255, verbose_name='Example Code'),
            preserve_default=False,
        ),
    ]
