# Generated by Django 2.1rc1 on 2018-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Base', '0005_auto_20180729_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfunction',
            name='function_format',
            field=models.CharField(max_length=500, verbose_name='Function Code Format'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='usage_format',
            field=models.CharField(max_length=500, verbose_name='Function Usage Format'),
        ),
    ]
