# Generated by Django 2.1rc1 on 2018-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Base', '0007_auto_20180808_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpackage',
            name='package_description',
            field=models.CharField(max_length=1000, verbose_name='Package Description'),
        ),
    ]
