# Generated by Django 2.1rc1 on 2018-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Base', '0009_auto_20180816_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwsubcategory',
            name='subcategory_explanation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
